### ISSUE TITLE
Issue with building templates

### ISSUE THREAD

**Issue by dextel2** [sofn-xyz/mailing-templates#6]
**Describe the bug**
I am facing issue with building the project.

![image](https://user-images.githubusercontent.com/16697307/206167039-6fc01559-df1a-425f-8293-6710738035a9.png)

**Expected behavior**
- The templates should build
- The project should run/build

- OS: Windows
- Browser Chrome
- Version 108.x

**Additional context**
I am trying to learn to build email templates with mailing but couldn't run/build/
I haven't changed the existing package.json

**Comment by DevPriyanshu** [comment]
facing the same issue, Windows 11
![image](https://user-images.githubusercontent.com/72295861/207006173-107073df-3114-4656-a55a-2abbe91018ae.png)

**Comment by alexfarrill** [comment]
Mailing does not currently run on Windows, however we would love a PR that fixes that.  I am closing this issue for now, but https://github.com/sofn-xyz/mailing/issues/172 is our ticket to support Windows.  I'll reference this discussion there as well.  Pull requests welcome!
